### PR TITLE
migrate tryfirst mark to hookimpl compat

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
this one is a blocker for https://github.com/pytest-dev/pytest/pull/9118 
its not time critical, but a swift release would be really nice for my progress on the other pr

**Comment by RonnyPfannschmidt** [comment]
closing in favor of #549 which was created by @nicoddemus and solves it more clean

**Comment by nicoddemus** [comment]
Oh sorry I did not notice this one before I opened #549. 👍

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus yours was opened earlier as mine was only completed later

**Pull request closed without merging**
