### PR TITLE
add option to append coverage instead of deleting the .coverage file …

### LINKED ISSUE #79: append coverage over several runs
I am migrating test to py.test + coverage.

previously we ran the tests with `coverage run -a manage.py test sms`

to append the coverage of all tests. pytest-cov does always erase the .coverage file.

I'd like an option --cov-append that will combine the coverage of all test results

### PR DESCRIPTION
**Pull request by cleder**
…fixes #79

### CODE REVIEW

**Comment by ionelmc** [comment]
Hey. Thanks for making the change :)

But can you rename the option to `--cov-append`? All the other options start with `--cov`.

**Comment by schlamar** [comment]
We should have a test for this.

**Comment by cleder** [comment]
added tests and some documentation to README

**Comment by ionelmc** [comment]
I was wondering if we'd be better of with assertions on stdout (like here https://github.com/pytest-dev/pytest-cov/blob/master/tests/test_pytest_cov.py#L230-L235). That would ensure the loading works properly (your current assertions with the size might pass if you remove ``--cov-append``). What do you think?

**Comment by ionelmc** [comment]
Alright, this is included in master and fixed up a bit for xdist support. Thanks.

**Comment by aldanor** [comment]
Wonder if the coverage is persisted between runs? (in which case, how would it be possible to reset it so it still gets combined for all environments but not across different runs?)

**Comment by ionelmc** [comment]
@aldanor I think you are looking for something like https://github.com/ionelmc/python-nameless/blob/master/tox.ini#L118-L122

**Comment by aldanor** [comment]
@ionelmc I see, thanks. Feels a bit like a hack of course, because if you pass environments explicitly, e.g. `-e py27 -e py34`, this wouldn't work..

I guess the best use case would be gathering combined coverage for all Python versions within one run -- isn't it quite common?

**Comment by ionelmc** [comment]
@aldanor pytest don't support multiple python version testing, so we can't do anything special regarding that in pytest-cov. It's something in Tox's domain - it it has some inconveniences as you saw. If you want to use detox see [this](https://hynek.me/articles/testing-packaging/).

**Comment by The-Compiler** [comment]
One could probably write a tox plugin to do that though.

**Pull request closed without merging**
