### PR TITLE
ci: Travis: dist=xenial

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Only found https://github.com/pytest-dev/pytest-cov/blob/master/ci/templates/.travis.yml now - I assume it should go through it instead?

**Comment by ionelmc** [comment]
Yeah ... saves lots of typing.

**Comment by blueyed** [comment]
Looks good, but pypy might still fail/hang: https://travis-ci.org/pytest-dev/pytest-cov/jobs/503572051

**Comment by ionelmc** [comment]
I rebased it for you. That pypy test should be skipped now (xdist is very lousy on pypy).

**Comment by ionelmc** [comment]
@blueyed one question tho: why `cache: false` instead of `cache: pip`?

**Comment by blueyed** [comment]
@ionelmc 
Travis caches get downloaded from S3(?), which is similar to using pip via CDN and (hopefully) http caching.
This gets rid of overhead of managing the cache.

**Pull request merged**
