### PR TITLE
Implement --cov-reset option that resets accumulated --cov directorie…

### PR DESCRIPTION
**Pull request by dsegan**
Implement --cov-reset option that resets accumulated --cov directories.

Don't seem to be able to link to an issue, so here it is: https://github.com/pytest-dev/pytest-cov/issues/460

FWIW, the tests here are the integration tests in line with the rest of them, though we could arguably have a simple (and much faster) unit test that just checks if the options are modified correctly.

### CODE REVIEW

**Comment by dsegan** [comment]
Don't seem to be able to link this to an issue, so here it is: https://github.com/pytest-dev/pytest-cov/issues/460

**Comment by dsegan** [comment]
Hi, thanks for taking a look at this earlier @ionelmc: and here's another friendly ping to get it merged if it looks fine :)

If there's something I need to do to get it merged, do let me know (eg. signing off on something).

**Comment by ionelmc** [comment]
Nop, I just forgot about this.

**Comment by dsegan** [comment]
Thanks!

**Pull request merged**
