### PR TITLE
Fix docs building

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by ionelmc** [comment]
Seems fine to me, assuming it renders correctly.

**Comment by ssbarnea** [comment]
@ionelmc Can you please fix the integration with readthedocs? I do not see that app building this pull request so we cannot be sure about the outcome.

I do not have access to readthedocs pytest-cov project settings neither to this repository settings on github to enable the PR building using RTD service. Tx.

PS. My RTD account is the same as github one.

**Comment by ionelmc** [comment]
Invited now.

**Comment by ionelmc** [comment]
Do i need to do anything else here?

**Pull request closed without merging**
