### PR TITLE
Specify file output

### PR DESCRIPTION
**Pull request by unholysampler**
Add support for specifying output location for html, xml, and annotate report. Fixes issue #97.

### CODE REVIEW

**Comment by unholysampler** [comment]
Installed python2.6 locally and am trying to figure out why the following check is failing, even though it works in other versions and the output is the same.

```
    result.stderr.fnmatch_lines([
        '*argument --cov-report: output specifier not supported for: "term:%s"*' % DEST_DIR,
    ])
```

**Comment by ionelmc** [comment]
I suspect the arg parser used there (on 2.6) has some issues ... 

You could have something like this in the tests:
```
    result.stderr.fnmatch_lines([
        '*argument --cov-report: *',
    ] if tuple(sys.python_version[:2]) == (2, 6) else [
        '*argument --cov-report: output specifier not supported for: "term:%s"*' % DEST_DIR,
    ])
```

**Comment by ionelmc** [comment]
Note that we have to support 2.6, at least on some level, because pytest still supports 2.6.

**Comment by ionelmc** [comment]
Thanks!

**Pull request merged**
