### PR TITLE
introduced f-strings

### PR DESCRIPTION
**Pull request by marksmayo**
converted format strings to more modern f-strings

### CODE REVIEW

**Comment by cclauss** [comment]
@marksmayo Did you use [flynt](https://pypi.org/project/flynt/) or [pyupgrade](https://pypi.org/project/pyupgrade)?  Doing these conversions manually may introduce bugs.

**Comment by marksmayo** [comment]
Absolutely used flynt for the f-strings. Doesn't always get them all, but
it's pretty awesome!

**Review by ionelmc — APPROVED** [review]
Seems fine. Might need to rebase this to make other PRs less painful.

**Comment by cclauss** [comment]
@ionelmc Can you please approve the workflow run?

**Review by cclauss — APPROVED** [review]

**Comment by ionelmc** [comment]
Rebased in master. Will release in 4.1 later today if no objections.

**Pull request closed without merging**
