### PR TITLE
Handle precision for fail-under option

### PR DESCRIPTION
**Pull request by ionelmc**

### CODE REVIEW

**Comment by ionelmc** [comment]
@nedbat I am hoping I can use `display_covered` and `should_fail_under` from `coverage.results` without worries of them disappearing in a future coverage version.

**Comment by nedbat** [comment]
> @nedbat I am hoping I can use `display_covered` and `should_fail_under` from `coverage.results` without worries of them disappearing in a future coverage version.

I'm not sure how best to make that promise. I'd be inclined to move them to a new public module.  For now, know that things don't change much, and we'll hear about it if it breaks.

**Comment by Colin-b** [comment]
Hello @ionelmc 

Do you have a planning in mind to release this feature?

Thanks again !

**Comment by ionelmc** [comment]
Just released.

**Pull request merged**
