### PR TITLE
FIx pyproject.toml pytest syntax

### PR DESCRIPTION
**Pull request by jennydaman**

### CODE REVIEW

**Review by RonnyPfannschmidt — COMMENTED** [review]
The example is correct ini as is

**Comment by jennydaman** [comment]
Please see the upstream documentation:

https://docs.pytest.org/en/stable/reference/customize.html#pyproject-toml

**Comment by RonnyPfannschmidt** [comment]
The example here is for the ini file itself

**Comment by jennydaman** [comment]
Sorry I missed that detail.

**Pull request closed without merging**
