### PR TITLE
Add project structure to Usage

### PR DESCRIPTION
**Pull request by sylhare**
Hi,

I have added the project structure to the usage part, because I felt like it was not clear at first how to use it only based on just the command.

With the tree view, it appears more clearly (at least to me) what you need to put for it to work.
If you think that this change is 👍  maybe there are other places in the doc I need to add it? Or stuff I need to do for this pull request to be accepted.
If you thing the change is 👎  then sorry 😅 

Thanks

### CODE REVIEW

**Comment by ionelmc** [comment]
A better way is to point out to https://github.com/pytest-dev/pytest-cov/tree/master/examples and not change the intro section to a project layout overview.

**Comment by sylhare** [comment]
Well, the examples are not very clear, should I add an example that correspond to the intro with the command to get the same thing as the intro?
Then we can add a link toward that in the intro as you suggest.

**Comment by ionelmc** [comment]
Perhaps https://github.com/pytest-dev/pytest-cov/blob/master/examples/README.rst could be edited to have an overview of commands to run, usage instructions and such.

If we add layout stuff in the main readme then we open a can of worms cause it's a too big subject to have.

Then again, I don't really understand what prompted this PR. Perhaps explain what problems you hit when you started using pytest/cov?

**Comment by sylhare** [comment]
I opened this PR because it didn't look obvious to me how to use it when looking at the usage part.
Sure, I made it work, but I wanted to make it more user friendly so that even a beginner could understand it at first glance.

But as you say, we don't want to update the readme too much, so we can just add an example in `./examples/` that correspond to the usage, add some information there.

**Comment by sylhare** [comment]
I guess it is not very needed, I will close it then.

**Pull request closed without merging**
