### PR TITLE
Add conda-forge badge to README

### PR DESCRIPTION
**Pull request by nicoddemus**
Adds a badge with the conda-forge version of `pytest-cov`, of which I'm one of the maintainers of the package. 

The result can be seen [in my fork](https://github.com/nicoddemus/pytest-cov/tree/conda-forge-badge). 😉

### CODE REVIEW

**Comment by nicoddemus** [comment]
Also added Python 3.7 as a supported version to `setup.py`. 👍

**Comment by ionelmc** [comment]
Huh ... how do you release there? Do they build the platform-specific releases for you?

**Comment by nicoddemus** [comment]
The process is a little complex the first time you see it, but:

To create a new package, you submit a recipe to [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes). 

Once that gets approved, a new ["feedstock" repository](https://github.com/conda-forge/pytest-cov-feedstock on GitHub is created, with the maintainers that submitted the initial recipe to staged-recipes getting write access.

When new releases of the package are made to PyPI, a bot will automatically [open a PR](https://github.com/conda-forge/pytest-cov-feedstock/pull/13) updating the conda-recipe. When that gets merged, the CI will build and upload the updated packages.

This is explained in more details here: https://conda-forge.org/

**Comment by ionelmc** [comment]
Yeah but I still don't get why https://anaconda.org/conda-forge/pytest-cov has only 2.5.1 for plaform specifics and 2.6.0 for noarch.

**Comment by nicoddemus** [comment]
`2.5.1` was first published on that channel over 1 year and 3 months ago. Nearly two months ago the bot noticed that the package could be made `noarch`, so it pushed https://github.com/conda-forge/pytest-cov-feedstock/pull/12 to add the `noarch` flag and then `2.5.1` build `1` (`noarch/pytest-cov-2.5.1-py_1.tar.bz2`) was published. Now all builds onward should also be `noarch`.

**Comment by ionelmc** [comment]
Rebased manually.

**Pull request closed without merging**
