### PR TITLE
Add in pre commit hook

### PR DESCRIPTION
**Pull request by EigenJT**
Added in `.pre-commit-hooks.yaml` to allow use with https://github.com/pre-commit/pre-commit

### CODE REVIEW

**Comment by ionelmc** [comment]
I guess this would only make it run a bare pytest? How would this work?

**Comment by EigenJT** [comment]
Main use case I thought about was maintaining a required level of test
coverage before committing/pushing.

**Comment by ionelmc** [comment]
Well ok. I'm not sure how this would be used. Some documentation is needed about the typical usage.

**Comment by hukkinj1** [comment]
IMO this is not the right place for this hook. Should go to https://github.com/pytest-dev/pytest (if accepted by the maintainers) or a separate mirror repository.

The general pytest hook can then be extended with
```yaml
additional_dependencies: [pytest-cov]
args: [--cov, --cov-fail-under=95]
```
by the user, in order to add pytest-cov and coverage checking on top.

Even then this is probably a bad configuration because the user will need to list each and every project dependency in `additional_dependencies` to make the tests work...

**Comment by graingert** [comment]
pre-commit hooks run in an isolated virtual environment, for pytest you need to be able to install your test extra deps for your tests to work

**Comment by ssbarnea** [comment]
Sorry but pre-commit linting step has nothing to so with producing coverage reports. Running tests is a time consuming operation, clearly not something you want to bundle with coverage.

**Pull request closed without merging**
