### PR TITLE
Next release

### PR DESCRIPTION
**Pull request by ionelmc**
So the plan is to upload it on Monday. Comment if I got something wrong in the files.

After this release I guess we start cutting compatibility with old stuff and then we see about #337. 

@nedbat, @graingert

### CODE REVIEW

**Comment by nedbat** [comment]
I would love to get #342 merged before that release.

**Comment by nedbat** [comment]
I am very close to merging #345, but I think I need to make a change in coverage.py first.  Can we hold off a day or two?

**Comment by ionelmc** [comment]
We can do anything, that date ain't written in stone. But we can also do a 2.9.0 with just the context stuff - to not feel pressed to make a coveragepy release quickly. What will it be?

**Comment by nedbat** [comment]
I was going to change an API from using glob to using regex.  But I can handwave over that.  Let me write the docs, and then #345 will be ready to merge.

**Comment by nedbat** [comment]
I've changed my mind again. Go ahead and do this release without #345.

**Comment by nedbat** [comment]
Or wait a day or two for me.  Your choice.

**Comment by nedbat** [comment]
#345 is ready to go. Please merge it and then release.

**Comment by ionelmc** [comment]
@nicoddemus any idea why I can't cancel appveyor builds on this project?

**Comment by ionelmc** [comment]
So it looks like this might be broken with xdist 0.30, ooof.

**Comment by blueyed** [comment]
Looks like it might be only due to the header?

> remains unmatched: '*- coverage: platform *, python * -*'

**Comment by ionelmc** [comment]
Workers don't appear to return coverage data. I suspect this is the cause https://github.com/pytest-dev/pytest-xdist/pull/448/files#r330989777

**Comment by ionelmc** [comment]
Mkay so it looks like pytest 5.x and xdist 0.30 break the non-collocated mode (xdist in popen/ssh mode). Pytest 4.6 or xdist 0.29 or earlier work fine. 

Since no one complained yet about releasing delays I'll spend some time investigating this.

**Comment by ionelmc** [comment]
Actually screw it, I'll release it as is, 3.8 is broken as well, and previous pytest-cov release is even more broken.

**Pull request merged**
