### PR TITLE
Add support for 'skip_covered' option in terminal report section

### LINKED ISSUE #114: Add support for 'skip_covered' under reporting
coverage 4.0 added support for `skip_covered` option in the `[report]` section.

> `skip_covered` (boolean, default False): Don’t include files in the report that are 100% covered files. See Coverage summary for more information.[1] 

This lib doesn't seem to recognise and pass this parameter to the coverage runner.

Best. 

[1] https://coverage.readthedocs.io/en/coverage-4.0.3/config.html#report

### PR DESCRIPTION
**Pull request by theskumar**
This is a working implementation and works fine with `.coveragerc` and `setup.cfg`.

I've not added relevant docs and test, as i'm still trying to understand those. 

@ionelmc if this looks good, i'll try to add docs and tests. 

Ref: http://coverage.readthedocs.io/en/latest/api_coverage.html#coverage.Coverage.report

closes #114

### CODE REVIEW

**Comment by ionelmc** [comment]
Looks fine. If you need any help with the tests just ping me. (I suspect you can do something like `test_coveragerc`)

**Comment by theskumar** [comment]
Thanks. 

I've updated the PR with 1) compatibility with older version of coverage 2) tests 3) docs. 

@ionelmc It would be great if you can have look & squash/merge/release.

Best.

**Comment by ionelmc** [comment]
One question tho, sorry for bringing this up so late: Shouldn't we allow users to have skip_covered option when they use `--cov-report=term-missing`? In that case we'd only need to change a bit the option  parser to allow stuff like `--cov-report=term-missing:skip-covered` and `--cov-report=term:skip-covered`. What do you think?

**Comment by theskumar** [comment]
so currently this is achievable with
```
--cov-report=term-missing --cov-report=term-skip-covered
```
I agree that the suggested api is cleaner, I just when the existing style... i.e. `term`, `term-missing`. 
Happy to change it, if you prefer.

**Comment by ionelmc** [comment]
I think it's better for the users, not obvious that `--cov-report=term-missing` and `--cov-report=term-skip-covered` actually compose, at least not in my head.

**Comment by theskumar** [comment]
Agreed. I'll take a stab at changing it.

One thing i didn't understand while working on this is: how does the `skip_covered` setting in `.coveragerc` started to get recognised by only adding an addition parameter to `self.cov.report(...)`.

**Comment by ionelmc** [comment]
I suspect it's loaded when the cov object is created (and `.coveragerc` is loaded). We should have a test for this, just in case something regresses.

**Comment by ionelmc** [comment]
@theskumar hey, still have time for this?

**Comment by theskumar** [comment]
So i've been looking into it, and it's take more time than I aspected. I guess, mostly in the validate_report function. Happy to have someone take over this feature. I'm bit occupied as well, so just getting only short bursts of time to work.

**Comment by theskumar** [comment]
@ionelmc I've updated the cli usages as suggested by you. And separated the `.coveragerc` test.

Let me know, if anything else needs to be done for this to be merged. Thanks.

**Comment by ionelmc** [comment]
Looks good, thanks. Gonna wait just a bit for Travis to finish.

**Comment by theskumar** [comment]
test failing :/ taking a look and will get back.

**Comment by theskumar** [comment]
Updated PR with fix. Pretty sure, this will not fail!

**Comment by ionelmc** [comment]
Alright, thanks for the changes.

**Pull request merged**
