### PR TITLE
Remove use of rsyncdir

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #557

### CODE REVIEW

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
That particular example and the loops are actually correct and needed as is

We might need to revise the rsync dir details given thst we don't have a coverage combine test atm

**Comment by ionelmc** [comment]
I'd remove it completely now. Best to deal with the breakage now than down the road when support for that option is gone.

**Comment by ssbarnea** [comment]
@ionelmc Any chance to approve it?

**Comment by tomhamiltonstubber** [comment]
Any word here folks?

**Comment by ionelmc** [comment]
Whoops missed this. Looks all good.

**Comment by jonyscathe** [comment]
Any chance of a pytest-cov to get this fix in?
Would be great to git rid of deprecation warnings filters in all of my projects and this was fixed up months ago in master.

**Comment by tomhamiltonstubber** [comment]
Please can we get a release here?

**Comment by ionelmc** [comment]
Later today there will be a 4.1 release (if no objections).

**Pull request merged**
